### ISSUE TITLE
Add Sjors Provoost transcripts - Tracking issue

### ISSUE THREAD

**Issue by edilmedeiros** [bitcointranscripts/bitcointranscripts#407]
This issue will be updated to reflect the current state of integration of Sjors Provoost's transcripts mentioned in #388. 

- [x] [03.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/03.txt): #406 
- [x] [04.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/04.txt): #410 
- [x] [05.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/05.txt): [already present in the transcripts pool.](https://github.com/bitcointranscripts/bitcointranscripts/blob/47f9d662c77229e3dea312cd4291b3a232aab19d/bitcoin-explained/scaling-bitcoin-with-the-erlay-protocol.md)
- [x] [09.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/09.txt): #411 
- [x] [13.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/13.txt): [already present in the transcripts pool.](https://github.com/bitcointranscripts/bitcointranscripts/blob/47f9d662c77229e3dea312cd4291b3a232aab19d/bitcoin-explained/bitcoin-core-v21-supports-tor-v3.md)
- [x] [14.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/14.txt): #413
- [x] [15.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/15.txt): #424
- [x] [17.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/17.txt): #425
- [x] [18.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/18.txt): [already present in the transcripts pool.](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/bitcoin-explained/erebus-attacks-and-how-to-stop-them-with-asmap.md)
- [x] [21.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/21.txt): #426
- [x] [28.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/28.txt): [already present in the transcript pool](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/bitcoin-explained/explaining-bitcoin-addresses.md).
- [x] [32.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/32.txt): [already present in the transcript pool](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/bitcoin-explained/explaining-segregated-witness.md).
- [x] [49.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/49.txt): #428
- [x] [77.txt](https://github.com/Sjors/nado-book/blob/d6e00aebc31164fbbcf5ad235b7874f282e0ff1c/transcripts/77.txt): #427

**Comment by edilmedeiros** [comment]
@kouloumos, they are all there for review.

**Comment by kouloumos** [comment]
All transcripts have now been (finally) merged! Thank you very much @edilmedeiros for taking the time to do this!
We hope to see more of your contributions in Bitcoin Transcripts as well as the in the overall Bitcoin Dev Project!
